version: "3"

networks:
  frontend:
  backend:

services:
  nginx:
    container_name: "nginx"
    networks:
      - frontend
      - backend
    build: "./nginx/"
    ports:
      - "80:80"
    volumes:
      - "./nginx/etc/nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/var/log/nginx:/var/log/nginx"
      - "/Users/lucas/gitlab/dashboard:/var/www/html/dashboard"
      - "/Users/lucas/gitlab/local:/var/www/html/local"

  php:
    container_name: "php"
    networks:
      - backend
    build: "./php/"
    expose:
      - 9000
    volumes:
      - "/Users/lucas/gitlab/dashboard:/var/www/html/dashboard"
      - "/Users/lucas/gitlab/local:/var/www/html/local"

  mysql:
    container_name: "mysql"
    networks:
      - backend
    ports:
      - "3306:3306"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command: mysqld --max_allowed_packet=1024M --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql/var/lib/mysql:/var/lib/mysql"

  phpmyadmin:
    container_name: phpmyadmin
    networks:
      - frontend
      - backend
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql

  redis:
    container_name: redis
    networks:
      - backend
    build: ./redis/
    volumes:
          - ./log/supervisor:/var/log/supervisor
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"
      - "7007:7007"